"""connect the table 

Revision ID: 030f9cd9e586
Revises: 3621f7a76b37
Create Date: 2025-10-19 21:13:37.114070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '030f9cd9e586'
down_revision: Union[str, Sequence[str], None] = '3621f7a76b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
def upgrade():
    op.alter_column(
        'income',
        'tea',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="NULLIF(tea, '')::double precision"
    )

    op.alter_column(
        'income',
        'water',
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="NULLIF(water, '')::double precision"
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'water',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('income', 'tea',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
