"""Add new_column to projects

Revision ID: 0e35aefe6e32
Revises: 83c7461acb9d
Create Date: 2025-08-03 02:06:00.858712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e35aefe6e32'
down_revision: Union[str, Sequence[str], None] = '83c7461acb9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Production', sa.Column('delete_index_hr', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Production', 'delete_index_hr')
    # ### end Alembic commands ###
