"""create user_table

Revision ID: 10be1dcfd4e0
Revises: 346e80920636
Create Date: 2025-12-18 13:24:56.150730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10be1dcfd4e0'
down_revision: Union[str, Sequence[str], None] = '346e80920636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_setting_income_id'), 'setting_income', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setting_income_id'), table_name='setting_income')
    op.drop_table('setting_income')
    # ### end Alembic commands ###
