"""connect the table 

Revision ID: 237af3b86a6c
Revises: 67ae9e7e5763
Create Date: 2025-10-19 20:00:17.320438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '237af3b86a6c'
down_revision: Union[str, Sequence[str], None] = '67ae9e7e5763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'income',
        sa.Column('tea', sa.Float(), nullable=False, server_default='0')
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('extra', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('income', 'water')
    op.drop_column('income', 'tea')
    # ### end Alembic commands ###
