"""Add new_column to projects

Revision ID: 4cc224f727c8
Revises: 
Create Date: 2025-08-02 22:23:56.028540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc224f727c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Production',
    sa.Column('sno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('DieId', sa.JSON(), nullable=False),
    sa.Column('overall_production', sa.JSON(), nullable=False),
    sa.Column('overall_time', sa.JSON(), nullable=False),
    sa.Column('overtime', sa.JSON(), nullable=False),
    sa.Column('price', sa.JSON(), nullable=False),
    sa.Column('monthy_pay', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('income',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('Die',
    sa.Column('DieId', sa.String(), nullable=False),
    sa.Column('DieName', sa.String(), nullable=False),
    sa.Column('CompanyName', sa.String(), nullable=False),
    sa.Column('Materials', sa.String(), nullable=False),
    sa.Column('Cavity', sa.String(), nullable=False),
    sa.Column('Weight', sa.String(), nullable=False),
    sa.Column('Pro_hr_count', sa.String(), nullable=False),
    sa.Column('Price', sa.String(), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('DieId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Die')
    op.drop_table('income')
    op.drop_table('Production')
    # ### end Alembic commands ###
