"""Add new_column to projects

Revision ID: 5ba803316f78
Revises: 7edd886953e2
Create Date: 2025-09-07 21:34:33.031446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba803316f78'
down_revision: Union[str, Sequence[str], None] = '7edd886953e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('extra', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'extra')
    # ### end Alembic commands ###
