"""Add new_column to projects

Revision ID: 67a3d6786ab3
Revises: 0e35aefe6e32
Create Date: 2025-09-06 21:18:03.907853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67a3d6786ab3'
down_revision: Union[str, Sequence[str], None] = '0e35aefe6e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Die', 'DieName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Die', 'DieName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
