"""create user_table

Revision ID: 7978a7077bd0
Revises: a98b2f14bd6b
Create Date: 2026-01-08 23:43:05.005098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7978a7077bd0'
down_revision: Union[str, Sequence[str], None] = 'a98b2f14bd6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_come_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('income', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pre_come_user_id'), 'pre_come_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pre_come_user_id'), table_name='pre_come_user')
    op.drop_table('pre_come_user')
    # ### end Alembic commands ###
