"""Add new_column to projects

Revision ID: 7edd886953e2
Revises: 67a3d6786ab3
Create Date: 2025-09-07 18:55:26.655543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7edd886953e2'
down_revision: Union[str, Sequence[str], None] = '67a3d6786ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Die', 'DieName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint('uix_die_name_cavity', 'Die', ['DieName', 'Cavity'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_die_name_cavity', 'Die', type_='unique')
    op.alter_column('Die', 'DieName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
