"""Add new_column to projects

Revision ID: 83c7461acb9d
Revises: 9c4538f67318
Create Date: 2025-08-03 00:59:42.095020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83c7461acb9d'
down_revision: Union[str, Sequence[str], None] = '9c4538f67318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Production', sa.Column('date', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'Production', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Production', type_='unique')
    op.drop_column('Production', 'date')
    # ### end Alembic commands ###
