"""connect the table 

Revision ID: d19d4b09c006
Revises: 5042e83854c0
Create Date: 2025-10-19 20:32:41.808562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19d4b09c006'
down_revision: Union[str, Sequence[str], None] = '5042e83854c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'tea',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('income', 'water',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('income', 'water',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('income', 'tea',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
